// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/gen0cide/laforge/ent/fileextract"
	"github.com/gen0cide/laforge/ent/predicate"
	"github.com/gen0cide/laforge/ent/tag"
)

// FileExtractQuery is the builder for querying FileExtract entities.
type FileExtractQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	predicates []predicate.FileExtract
	// eager-loading edges.
	withTag *TagQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (feq *FileExtractQuery) Where(ps ...predicate.FileExtract) *FileExtractQuery {
	feq.predicates = append(feq.predicates, ps...)
	return feq
}

// Limit adds a limit step to the query.
func (feq *FileExtractQuery) Limit(limit int) *FileExtractQuery {
	feq.limit = &limit
	return feq
}

// Offset adds an offset step to the query.
func (feq *FileExtractQuery) Offset(offset int) *FileExtractQuery {
	feq.offset = &offset
	return feq
}

// Order adds an order step to the query.
func (feq *FileExtractQuery) Order(o ...OrderFunc) *FileExtractQuery {
	feq.order = append(feq.order, o...)
	return feq
}

// QueryTag chains the current query on the tag edge.
func (feq *FileExtractQuery) QueryTag() *TagQuery {
	query := &TagQuery{config: feq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := feq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := feq.sqlQuery()
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(fileextract.Table, fileextract.FieldID, selector),
			sqlgraph.To(tag.Table, tag.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, fileextract.TagTable, fileextract.TagColumn),
		)
		fromU = sqlgraph.SetNeighbors(feq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FileExtract entity in the query. Returns *NotFoundError when no fileextract was found.
func (feq *FileExtractQuery) First(ctx context.Context) (*FileExtract, error) {
	nodes, err := feq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{fileextract.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (feq *FileExtractQuery) FirstX(ctx context.Context) *FileExtract {
	node, err := feq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FileExtract id in the query. Returns *NotFoundError when no id was found.
func (feq *FileExtractQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = feq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{fileextract.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (feq *FileExtractQuery) FirstIDX(ctx context.Context) int {
	id, err := feq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only FileExtract entity in the query, returns an error if not exactly one entity was returned.
func (feq *FileExtractQuery) Only(ctx context.Context) (*FileExtract, error) {
	nodes, err := feq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{fileextract.Label}
	default:
		return nil, &NotSingularError{fileextract.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (feq *FileExtractQuery) OnlyX(ctx context.Context) *FileExtract {
	node, err := feq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID returns the only FileExtract id in the query, returns an error if not exactly one id was returned.
func (feq *FileExtractQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = feq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{fileextract.Label}
	default:
		err = &NotSingularError{fileextract.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (feq *FileExtractQuery) OnlyIDX(ctx context.Context) int {
	id, err := feq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FileExtracts.
func (feq *FileExtractQuery) All(ctx context.Context) ([]*FileExtract, error) {
	if err := feq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return feq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (feq *FileExtractQuery) AllX(ctx context.Context) []*FileExtract {
	nodes, err := feq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FileExtract ids.
func (feq *FileExtractQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := feq.Select(fileextract.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (feq *FileExtractQuery) IDsX(ctx context.Context) []int {
	ids, err := feq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (feq *FileExtractQuery) Count(ctx context.Context) (int, error) {
	if err := feq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return feq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (feq *FileExtractQuery) CountX(ctx context.Context) int {
	count, err := feq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (feq *FileExtractQuery) Exist(ctx context.Context) (bool, error) {
	if err := feq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return feq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (feq *FileExtractQuery) ExistX(ctx context.Context) bool {
	exist, err := feq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (feq *FileExtractQuery) Clone() *FileExtractQuery {
	if feq == nil {
		return nil
	}
	return &FileExtractQuery{
		config:     feq.config,
		limit:      feq.limit,
		offset:     feq.offset,
		order:      append([]OrderFunc{}, feq.order...),
		predicates: append([]predicate.FileExtract{}, feq.predicates...),
		withTag:    feq.withTag.Clone(),
		// clone intermediate query.
		sql:  feq.sql.Clone(),
		path: feq.path,
	}
}

//  WithTag tells the query-builder to eager-loads the nodes that are connected to
// the "tag" edge. The optional arguments used to configure the query builder of the edge.
func (feq *FileExtractQuery) WithTag(opts ...func(*TagQuery)) *FileExtractQuery {
	query := &TagQuery{config: feq.config}
	for _, opt := range opts {
		opt(query)
	}
	feq.withTag = query
	return feq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Source string `json:"source,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FileExtract.Query().
//		GroupBy(fileextract.FieldSource).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (feq *FileExtractQuery) GroupBy(field string, fields ...string) *FileExtractGroupBy {
	group := &FileExtractGroupBy{config: feq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := feq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return feq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		Source string `json:"source,omitempty"`
//	}
//
//	client.FileExtract.Query().
//		Select(fileextract.FieldSource).
//		Scan(ctx, &v)
//
func (feq *FileExtractQuery) Select(field string, fields ...string) *FileExtractSelect {
	selector := &FileExtractSelect{config: feq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := feq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return feq.sqlQuery(), nil
	}
	return selector
}

func (feq *FileExtractQuery) prepareQuery(ctx context.Context) error {
	if feq.path != nil {
		prev, err := feq.path(ctx)
		if err != nil {
			return err
		}
		feq.sql = prev
	}
	return nil
}

func (feq *FileExtractQuery) sqlAll(ctx context.Context) ([]*FileExtract, error) {
	var (
		nodes       = []*FileExtract{}
		_spec       = feq.querySpec()
		loadedTypes = [1]bool{
			feq.withTag != nil,
		}
	)
	_spec.ScanValues = func() []interface{} {
		node := &FileExtract{config: feq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, feq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := feq.withTag; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*FileExtract)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.Tag = []*Tag{}
		}
		query.withFKs = true
		query.Where(predicate.Tag(func(s *sql.Selector) {
			s.Where(sql.InValues(fileextract.TagColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.file_extract_tag
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "file_extract_tag" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "file_extract_tag" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.Tag = append(node.Edges.Tag, n)
		}
	}

	return nodes, nil
}

func (feq *FileExtractQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := feq.querySpec()
	return sqlgraph.CountNodes(ctx, feq.driver, _spec)
}

func (feq *FileExtractQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := feq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (feq *FileExtractQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   fileextract.Table,
			Columns: fileextract.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: fileextract.FieldID,
			},
		},
		From:   feq.sql,
		Unique: true,
	}
	if ps := feq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := feq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := feq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := feq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, fileextract.ValidColumn)
			}
		}
	}
	return _spec
}

func (feq *FileExtractQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(feq.driver.Dialect())
	t1 := builder.Table(fileextract.Table)
	selector := builder.Select(t1.Columns(fileextract.Columns...)...).From(t1)
	if feq.sql != nil {
		selector = feq.sql
		selector.Select(selector.Columns(fileextract.Columns...)...)
	}
	for _, p := range feq.predicates {
		p(selector)
	}
	for _, p := range feq.order {
		p(selector, fileextract.ValidColumn)
	}
	if offset := feq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := feq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FileExtractGroupBy is the builder for group-by FileExtract entities.
type FileExtractGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fegb *FileExtractGroupBy) Aggregate(fns ...AggregateFunc) *FileExtractGroupBy {
	fegb.fns = append(fegb.fns, fns...)
	return fegb
}

// Scan applies the group-by query and scan the result into the given value.
func (fegb *FileExtractGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := fegb.path(ctx)
	if err != nil {
		return err
	}
	fegb.sql = query
	return fegb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (fegb *FileExtractGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := fegb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (fegb *FileExtractGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(fegb.fields) > 1 {
		return nil, errors.New("ent: FileExtractGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := fegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (fegb *FileExtractGroupBy) StringsX(ctx context.Context) []string {
	v, err := fegb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (fegb *FileExtractGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = fegb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{fileextract.Label}
	default:
		err = fmt.Errorf("ent: FileExtractGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (fegb *FileExtractGroupBy) StringX(ctx context.Context) string {
	v, err := fegb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (fegb *FileExtractGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(fegb.fields) > 1 {
		return nil, errors.New("ent: FileExtractGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := fegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (fegb *FileExtractGroupBy) IntsX(ctx context.Context) []int {
	v, err := fegb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (fegb *FileExtractGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = fegb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{fileextract.Label}
	default:
		err = fmt.Errorf("ent: FileExtractGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (fegb *FileExtractGroupBy) IntX(ctx context.Context) int {
	v, err := fegb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (fegb *FileExtractGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(fegb.fields) > 1 {
		return nil, errors.New("ent: FileExtractGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := fegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (fegb *FileExtractGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := fegb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (fegb *FileExtractGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = fegb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{fileextract.Label}
	default:
		err = fmt.Errorf("ent: FileExtractGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (fegb *FileExtractGroupBy) Float64X(ctx context.Context) float64 {
	v, err := fegb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (fegb *FileExtractGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(fegb.fields) > 1 {
		return nil, errors.New("ent: FileExtractGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := fegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (fegb *FileExtractGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := fegb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (fegb *FileExtractGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = fegb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{fileextract.Label}
	default:
		err = fmt.Errorf("ent: FileExtractGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (fegb *FileExtractGroupBy) BoolX(ctx context.Context) bool {
	v, err := fegb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (fegb *FileExtractGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range fegb.fields {
		if !fileextract.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := fegb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fegb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (fegb *FileExtractGroupBy) sqlQuery() *sql.Selector {
	selector := fegb.sql
	columns := make([]string, 0, len(fegb.fields)+len(fegb.fns))
	columns = append(columns, fegb.fields...)
	for _, fn := range fegb.fns {
		columns = append(columns, fn(selector, fileextract.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(fegb.fields...)
}

// FileExtractSelect is the builder for select fields of FileExtract entities.
type FileExtractSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (fes *FileExtractSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := fes.path(ctx)
	if err != nil {
		return err
	}
	fes.sql = query
	return fes.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (fes *FileExtractSelect) ScanX(ctx context.Context, v interface{}) {
	if err := fes.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (fes *FileExtractSelect) Strings(ctx context.Context) ([]string, error) {
	if len(fes.fields) > 1 {
		return nil, errors.New("ent: FileExtractSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := fes.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (fes *FileExtractSelect) StringsX(ctx context.Context) []string {
	v, err := fes.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (fes *FileExtractSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = fes.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{fileextract.Label}
	default:
		err = fmt.Errorf("ent: FileExtractSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (fes *FileExtractSelect) StringX(ctx context.Context) string {
	v, err := fes.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (fes *FileExtractSelect) Ints(ctx context.Context) ([]int, error) {
	if len(fes.fields) > 1 {
		return nil, errors.New("ent: FileExtractSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := fes.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (fes *FileExtractSelect) IntsX(ctx context.Context) []int {
	v, err := fes.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (fes *FileExtractSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = fes.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{fileextract.Label}
	default:
		err = fmt.Errorf("ent: FileExtractSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (fes *FileExtractSelect) IntX(ctx context.Context) int {
	v, err := fes.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (fes *FileExtractSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(fes.fields) > 1 {
		return nil, errors.New("ent: FileExtractSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := fes.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (fes *FileExtractSelect) Float64sX(ctx context.Context) []float64 {
	v, err := fes.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (fes *FileExtractSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = fes.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{fileextract.Label}
	default:
		err = fmt.Errorf("ent: FileExtractSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (fes *FileExtractSelect) Float64X(ctx context.Context) float64 {
	v, err := fes.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (fes *FileExtractSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(fes.fields) > 1 {
		return nil, errors.New("ent: FileExtractSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := fes.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (fes *FileExtractSelect) BoolsX(ctx context.Context) []bool {
	v, err := fes.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (fes *FileExtractSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = fes.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{fileextract.Label}
	default:
		err = fmt.Errorf("ent: FileExtractSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (fes *FileExtractSelect) BoolX(ctx context.Context) bool {
	v, err := fes.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (fes *FileExtractSelect) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range fes.fields {
		if !fileextract.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for selection", f)}
		}
	}
	rows := &sql.Rows{}
	query, args := fes.sqlQuery().Query()
	if err := fes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (fes *FileExtractSelect) sqlQuery() sql.Querier {
	selector := fes.sql
	selector.Select(selector.Columns(fes.fields...)...)
	return selector
}
