// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/gen0cide/laforge/ent/filedownload"
	"github.com/gen0cide/laforge/ent/tag"
)

// FileDownloadCreate is the builder for creating a FileDownload entity.
type FileDownloadCreate struct {
	config
	mutation *FileDownloadMutation
	hooks    []Hook
}

// SetSourceType sets the source_type field.
func (fdc *FileDownloadCreate) SetSourceType(s string) *FileDownloadCreate {
	fdc.mutation.SetSourceType(s)
	return fdc
}

// SetSource sets the source field.
func (fdc *FileDownloadCreate) SetSource(s string) *FileDownloadCreate {
	fdc.mutation.SetSource(s)
	return fdc
}

// SetDestination sets the destination field.
func (fdc *FileDownloadCreate) SetDestination(s string) *FileDownloadCreate {
	fdc.mutation.SetDestination(s)
	return fdc
}

// SetTemplate sets the template field.
func (fdc *FileDownloadCreate) SetTemplate(b bool) *FileDownloadCreate {
	fdc.mutation.SetTemplate(b)
	return fdc
}

// SetMode sets the mode field.
func (fdc *FileDownloadCreate) SetMode(s string) *FileDownloadCreate {
	fdc.mutation.SetMode(s)
	return fdc
}

// SetDisabled sets the disabled field.
func (fdc *FileDownloadCreate) SetDisabled(b bool) *FileDownloadCreate {
	fdc.mutation.SetDisabled(b)
	return fdc
}

// SetMd5 sets the md5 field.
func (fdc *FileDownloadCreate) SetMd5(s string) *FileDownloadCreate {
	fdc.mutation.SetMd5(s)
	return fdc
}

// SetAbsPath sets the abs_path field.
func (fdc *FileDownloadCreate) SetAbsPath(s string) *FileDownloadCreate {
	fdc.mutation.SetAbsPath(s)
	return fdc
}

// AddTagIDs adds the tag edge to Tag by ids.
func (fdc *FileDownloadCreate) AddTagIDs(ids ...int) *FileDownloadCreate {
	fdc.mutation.AddTagIDs(ids...)
	return fdc
}

// AddTag adds the tag edges to Tag.
func (fdc *FileDownloadCreate) AddTag(t ...*Tag) *FileDownloadCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return fdc.AddTagIDs(ids...)
}

// Mutation returns the FileDownloadMutation object of the builder.
func (fdc *FileDownloadCreate) Mutation() *FileDownloadMutation {
	return fdc.mutation
}

// Save creates the FileDownload in the database.
func (fdc *FileDownloadCreate) Save(ctx context.Context) (*FileDownload, error) {
	var (
		err  error
		node *FileDownload
	)
	if len(fdc.hooks) == 0 {
		if err = fdc.check(); err != nil {
			return nil, err
		}
		node, err = fdc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FileDownloadMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = fdc.check(); err != nil {
				return nil, err
			}
			fdc.mutation = mutation
			node, err = fdc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(fdc.hooks) - 1; i >= 0; i-- {
			mut = fdc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fdc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (fdc *FileDownloadCreate) SaveX(ctx context.Context) *FileDownload {
	v, err := fdc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (fdc *FileDownloadCreate) check() error {
	if _, ok := fdc.mutation.SourceType(); !ok {
		return &ValidationError{Name: "source_type", err: errors.New("ent: missing required field \"source_type\"")}
	}
	if _, ok := fdc.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New("ent: missing required field \"source\"")}
	}
	if _, ok := fdc.mutation.Destination(); !ok {
		return &ValidationError{Name: "destination", err: errors.New("ent: missing required field \"destination\"")}
	}
	if _, ok := fdc.mutation.Template(); !ok {
		return &ValidationError{Name: "template", err: errors.New("ent: missing required field \"template\"")}
	}
	if _, ok := fdc.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New("ent: missing required field \"mode\"")}
	}
	if _, ok := fdc.mutation.Disabled(); !ok {
		return &ValidationError{Name: "disabled", err: errors.New("ent: missing required field \"disabled\"")}
	}
	if _, ok := fdc.mutation.Md5(); !ok {
		return &ValidationError{Name: "md5", err: errors.New("ent: missing required field \"md5\"")}
	}
	if _, ok := fdc.mutation.AbsPath(); !ok {
		return &ValidationError{Name: "abs_path", err: errors.New("ent: missing required field \"abs_path\"")}
	}
	return nil
}

func (fdc *FileDownloadCreate) sqlSave(ctx context.Context) (*FileDownload, error) {
	_node, _spec := fdc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fdc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (fdc *FileDownloadCreate) createSpec() (*FileDownload, *sqlgraph.CreateSpec) {
	var (
		_node = &FileDownload{config: fdc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: filedownload.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: filedownload.FieldID,
			},
		}
	)
	if value, ok := fdc.mutation.SourceType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: filedownload.FieldSourceType,
		})
		_node.SourceType = value
	}
	if value, ok := fdc.mutation.Source(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: filedownload.FieldSource,
		})
		_node.Source = value
	}
	if value, ok := fdc.mutation.Destination(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: filedownload.FieldDestination,
		})
		_node.Destination = value
	}
	if value, ok := fdc.mutation.Template(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: filedownload.FieldTemplate,
		})
		_node.Template = value
	}
	if value, ok := fdc.mutation.Mode(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: filedownload.FieldMode,
		})
		_node.Mode = value
	}
	if value, ok := fdc.mutation.Disabled(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: filedownload.FieldDisabled,
		})
		_node.Disabled = value
	}
	if value, ok := fdc.mutation.Md5(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: filedownload.FieldMd5,
		})
		_node.Md5 = value
	}
	if value, ok := fdc.mutation.AbsPath(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: filedownload.FieldAbsPath,
		})
		_node.AbsPath = value
	}
	if nodes := fdc.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   filedownload.TagTable,
			Columns: []string{filedownload.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: tag.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FileDownloadCreateBulk is the builder for creating a bulk of FileDownload entities.
type FileDownloadCreateBulk struct {
	config
	builders []*FileDownloadCreate
}

// Save creates the FileDownload entities in the database.
func (fdcb *FileDownloadCreateBulk) Save(ctx context.Context) ([]*FileDownload, error) {
	specs := make([]*sqlgraph.CreateSpec, len(fdcb.builders))
	nodes := make([]*FileDownload, len(fdcb.builders))
	mutators := make([]Mutator, len(fdcb.builders))
	for i := range fdcb.builders {
		func(i int, root context.Context) {
			builder := fdcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FileDownloadMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fdcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fdcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fdcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX calls Save and panics if Save returns an error.
func (fdcb *FileDownloadCreateBulk) SaveX(ctx context.Context) []*FileDownload {
	v, err := fdcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
