// Code generated by entc, DO NOT EDIT.

package servertask

import (
	"fmt"
	"io"
	"strconv"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the servertask type in the database.
	Label = "server_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldStartTime holds the string denoting the start_time field in the database.
	FieldStartTime = "start_time"
	// FieldEndTime holds the string denoting the end_time field in the database.
	FieldEndTime = "end_time"
	// FieldErrors holds the string denoting the errors field in the database.
	FieldErrors = "errors"
	// FieldLogFilePath holds the string denoting the log_file_path field in the database.
	FieldLogFilePath = "log_file_path"
	// EdgeServerTaskToAuthUser holds the string denoting the servertasktoauthuser edge name in mutations.
	EdgeServerTaskToAuthUser = "ServerTaskToAuthUser"
	// EdgeServerTaskToStatus holds the string denoting the servertasktostatus edge name in mutations.
	EdgeServerTaskToStatus = "ServerTaskToStatus"
	// EdgeServerTaskToEnvironment holds the string denoting the servertasktoenvironment edge name in mutations.
	EdgeServerTaskToEnvironment = "ServerTaskToEnvironment"
	// EdgeServerTaskToBuild holds the string denoting the servertasktobuild edge name in mutations.
	EdgeServerTaskToBuild = "ServerTaskToBuild"
	// EdgeServerTaskToGinFileMiddleware holds the string denoting the servertasktoginfilemiddleware edge name in mutations.
	EdgeServerTaskToGinFileMiddleware = "ServerTaskToGinFileMiddleware"
	// Table holds the table name of the servertask in the database.
	Table = "server_tasks"
	// ServerTaskToAuthUserTable is the table that holds the ServerTaskToAuthUser relation/edge.
	ServerTaskToAuthUserTable = "server_tasks"
	// ServerTaskToAuthUserInverseTable is the table name for the AuthUser entity.
	// It exists in this package in order to avoid circular dependency with the "authuser" package.
	ServerTaskToAuthUserInverseTable = "auth_users"
	// ServerTaskToAuthUserColumn is the table column denoting the ServerTaskToAuthUser relation/edge.
	ServerTaskToAuthUserColumn = "server_task_server_task_to_auth_user"
	// ServerTaskToStatusTable is the table that holds the ServerTaskToStatus relation/edge.
	ServerTaskToStatusTable = "status"
	// ServerTaskToStatusInverseTable is the table name for the Status entity.
	// It exists in this package in order to avoid circular dependency with the "status" package.
	ServerTaskToStatusInverseTable = "status"
	// ServerTaskToStatusColumn is the table column denoting the ServerTaskToStatus relation/edge.
	ServerTaskToStatusColumn = "server_task_server_task_to_status"
	// ServerTaskToEnvironmentTable is the table that holds the ServerTaskToEnvironment relation/edge.
	ServerTaskToEnvironmentTable = "server_tasks"
	// ServerTaskToEnvironmentInverseTable is the table name for the Environment entity.
	// It exists in this package in order to avoid circular dependency with the "environment" package.
	ServerTaskToEnvironmentInverseTable = "environments"
	// ServerTaskToEnvironmentColumn is the table column denoting the ServerTaskToEnvironment relation/edge.
	ServerTaskToEnvironmentColumn = "server_task_server_task_to_environment"
	// ServerTaskToBuildTable is the table that holds the ServerTaskToBuild relation/edge.
	ServerTaskToBuildTable = "server_tasks"
	// ServerTaskToBuildInverseTable is the table name for the Build entity.
	// It exists in this package in order to avoid circular dependency with the "build" package.
	ServerTaskToBuildInverseTable = "builds"
	// ServerTaskToBuildColumn is the table column denoting the ServerTaskToBuild relation/edge.
	ServerTaskToBuildColumn = "server_task_server_task_to_build"
	// ServerTaskToGinFileMiddlewareTable is the table that holds the ServerTaskToGinFileMiddleware relation/edge.
	ServerTaskToGinFileMiddlewareTable = "gin_file_middlewares"
	// ServerTaskToGinFileMiddlewareInverseTable is the table name for the GinFileMiddleware entity.
	// It exists in this package in order to avoid circular dependency with the "ginfilemiddleware" package.
	ServerTaskToGinFileMiddlewareInverseTable = "gin_file_middlewares"
	// ServerTaskToGinFileMiddlewareColumn is the table column denoting the ServerTaskToGinFileMiddleware relation/edge.
	ServerTaskToGinFileMiddlewareColumn = "server_task_server_task_to_gin_file_middleware"
)

// Columns holds all SQL columns for servertask fields.
var Columns = []string{
	FieldID,
	FieldType,
	FieldStartTime,
	FieldEndTime,
	FieldErrors,
	FieldLogFilePath,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "server_tasks"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"server_task_server_task_to_auth_user",
	"server_task_server_task_to_environment",
	"server_task_server_task_to_build",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeLOADENV      Type = "LOADENV"
	TypeCREATEBUILD  Type = "CREATEBUILD"
	TypeRENDERFILES  Type = "RENDERFILES"
	TypeDELETEBUILD  Type = "DELETEBUILD"
	TypeREBUILD      Type = "REBUILD"
	TypeEXECUTEBUILD Type = "EXECUTEBUILD"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeLOADENV, TypeCREATEBUILD, TypeRENDERFILES, TypeDELETEBUILD, TypeREBUILD, TypeEXECUTEBUILD:
		return nil
	default:
		return fmt.Errorf("servertask: invalid enum value for type field: %q", _type)
	}
}

// MarshalGQL implements graphql.Marshaler interface.
func (_type Type) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(_type.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (_type *Type) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*_type = Type(str)
	if err := TypeValidator(*_type); err != nil {
		return fmt.Errorf("%s is not a valid Type", str)
	}
	return nil
}
